[project]
name = "prefect-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "prefect>=3.2.9",
    "pydicom>=3.0.1",
    "pynetdicom>=2.0.2",
]
